- name: Check if prometheus namespace exists
  ansible.builtin.shell: |
    kubectl get namespace prometheus --no-headers || echo "NotFound"
  register: namespace_check
  failed_when: namespace_check.rc not in [0, 1] # Ignore errors if namespace doesn't exist
  become_user: jonathan

- name: Create prometheus namespace if it does not exist
  ansible.builtin.shell: |
    kubectl create namespace prometheus
  when: "'NotFound' in namespace_check.stdout"
  become_user: jonathan

- name: Copying prometheus files under tmp folder
  ansible.builtin.copy:
    src: ~/prometheus/prometheus-files
    dest: /tmp/prometheus-files
    owner: jonathan
    group: jonathan
    mode: "0755"
